"""empty message

Revision ID: c9ff4c1c83bf
Revises: c2ba4f5f54cd
Create Date: 2026-02-08 10:35:47.139292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ff4c1c83bf'
down_revision: Union[str, Sequence[str], None] = 'c2ba4f5f54cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sub_category_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('product_subcategory_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'sub_category', ['sub_category_id'], ['id'])
    op.drop_column('product', 'subcategory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_subcategory_id_fkey'), 'product', 'sub_category', ['subcategory_id'], ['id'])
    op.drop_column('product', 'sub_category_id')
    # ### end Alembic commands ###
